### ISSUE TITLE
Is it possible to use this app with Xamarin SDK?

### ISSUE THREAD

**Issue by shaharbukra** [Esri/mapbook-wpf#24]
How diffcult will it be to change it from the WPF SDK to the XAMARIN? :)
thinking about build one version to all 3 platform (Android, iOS and uwp :) )

Thanks,
Shahar.

**Comment by marastoica** [comment]
Should be pretty straight forward since the logic of the app is separated in the viewmodels, so you'd just need to build the Xamarin UI. You could keep everything in the same solution to make the best use of reusable code. I'd be happy to help. And if you could contribute your result to this repo, that would be fantastic! 

Here's a sample app that has Xamarin and WPF in the same solution, with maximum shared code. https://github.com/Esri/arcgis-runtime-demos-dotnet/tree/master/src/SimplePortalBrowser
